site_name: Flowgentic
site_url: https://github.com/stride-research/flowgentic
site_description: Agentic frameworks for HPC
repo_url: https://github.com/stride-research/flowgentic
repo_name: STRIDE-Lab/flowgentic

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture.md
  - Features:
      - Overview: features/overview.md
      - Memory: features/memory.md
      - Fault tolerance: features/fault_tolerance.md
      - Telemetry: features/telemetry.md
      - Miscellaneous: features/miscellaneous.md
  - Phased rollout:
      - Phased rollout: phased_rollout.md
  - API Reference: api/
  - Examples:
      - Chatbot: examples/chatbot.md
      - Sequential design pattern: examples/sequential.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      primary: indigo
      accent: deep purple
  logo: assets/logo.png
  favicon: assets/favicon.png

extra_css:
  - styles/overrides.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate_api_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_inheritance_diagram: false
            show_source: false
            inherited_members: true
            members_order: source
            separate_signature: true
            show_object_full_path: false
            show_root_full_path: false
            show_root_heading: true
            show_root_members_full_path: false
            show_root_toc_entry: true
            show_signature_annotations: true
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js